[package]
name = "rust_tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
rand = "0.9.1"
rtt-target = "0.6.1"
[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[features]
default = ["std"]
std=[]
